allsteps command
s-match/s-match-utils pull request #18
Opened 2016-12-27 13:27 UTC by DavidLeoni

S-Match CLI for a full match requires several runs to perform all needed steps, so each run needlessly spends time redoing initialization. This is a problem for batch processing. Ideally, for this scenario in the long term we would need a demon running as a service. As a quick improvement, with this pull request we just added the CLI command `allsteps`:

```
allsteps <source> <target> <output>    
Read source and target files, run all steps from 1 to 4 and write the output mapping
```
We also added some tests and a verbose flag `-v`: currently doesn't do much, but will be useful for future improvements

2017-01-10 20:28 UTC, autayeu requested changes

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
> +                            System.out.println("To preprocess a mapping, use context loaders that support IContextLoader ");
extra space at the end of string constant

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
> +    public static final String CMD_ALL_STEPS = "allsteps";
please refactor all the other commands into constants of the same style

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
> +     * @since 2.0.0
document

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
> +    public static final String VERBOSE_CMD_LINE_KEY = "-v";
document

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
> +            " -v                                         turn verbose mode on\n";
Verbose flag sort of duplicates the DEBUG and TRACE levels in logging. Yes, there is no logging here in the main (maybe it should be), but now there are two ways to increase messaging detail: verbose flag and logging level. They are not exactly equivalent, but then one should introduce verbosity level as a framework-wide thing to allow components to be verbose too. An alternative would be to keep logging level here as well and log extra info at DEBUG or TRACE. 

What do you think, which alternative is better?

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
>                          log.error("Not enough arguments for mappingFilter command.");
Given logging is already there, perhaps moving verbosity to logging would be the way to do it...

2017-01-10 20:28 UTC, autayeu commented on src/main/java/it/unitn/disi/smatch/CLI.java
> +                                System.out.println("INFO: No filtering was performed (too see why, run with flag " + VERBOSE_CMD_LINE_KEY + ")");
verbosity suggestion is also printed when verbose is on, ideally it should not

2017-01-10 20:28 UTC, autayeu commented on src/test/java/it/unitn/disi/smatch/test/CliTest.java
> + *
extra line

2017-01-25 13:02 UTC, DavidLeoni commented
I just removed the verbose flag, let's keep it simple and use plain logging for now.

2017-01-25 20:44 UTC, merged